services:
  - type: web
    name: tc-test-grpc-server
    runtime: node
    plan: free
    rootDir: grpc-server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
